---
title: "Olympic Weightlifting"
author: "Christopher Oh"
date: 2018-09-14
output:
  github_document:
    toc: true
    toc_depth: 6
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dpi = 300, out.width = "100%")
```

## Set Up

#### Library

```{r}
library(tidyverse)
library(knitr)
library(kableExtra)
```


#### Data

```{r, include=FALSE}
path_athlete <- "C://Users/logic/Downloads/120-years-of-olympic-history-athletes-and-results/athlete_events.csv"
path_region <- "C:/Users/logic/Downloads/120-years-of-olympic-history-athletes-and-results/noc_regions.csv"
```

```{r}
weightlifting <- 
  read_csv(path_athlete) %>% 
  filter(Sport %in% "Weightlifting") 
```

#### Color

```{r}
MEDAL_COLOR <- c(
  Gold = "#d4af37",
  Silver = "#c0c0c0",
  Bronze = "#cd7f32"
)
```

## Medal Counts

#### By country

```{r}
weightlifting %>%
  count(Team, Medal) %>% 
  filter(!is.na(Medal)) %>%
  # group_by(Team) %>% 
  # mutate(medal_count = sum(n))
  spread(Medal, n, fill = 0) %>% 
  mutate(Total = Bronze + Gold + Silver) %>%
  top_n(15, wt = Total) %>% 
  gather(Medal, `medal count`, Bronze:Silver) %>% 
  mutate(
    Team = fct_reorder(Team, -Total),
    Medal = fct_relevel(Medal, "Gold", "Silver")
  ) %>% 
  ggplot(aes(Team, `medal count`, fill = Medal)) +
  geom_col(position = position_dodge2()) +
  scale_fill_manual(values = MEDAL_COLOR) +
  labs(title = "Weightlifting Top 15 All-time Medal Counts in Olympics") +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(size = 6)
  )

weightlifting %>%
  filter(Sex %in% "M") %>%
  count(Team, Medal) %>% 
  filter(!is.na(Medal)) %>%
  # group_by(Team) %>% 
  # mutate(medal_count = sum(n))
  spread(Medal, n, fill = 0) %>% 
  mutate(Total = Bronze + Gold + Silver) %>%
  top_n(15, wt = Total) %>% 
  gather(Medal, `medal count`, Bronze:Silver) %>% 
  mutate(
    Team = fct_reorder(Team, -Total),
    Medal = fct_relevel(Medal, "Gold", "Silver")
  ) %>% 
  ggplot(aes(Team, `medal count`, fill = Medal)) +
  geom_col(position = position_dodge2()) +
  scale_fill_manual(values = MEDAL_COLOR) +
  labs(title = "Weightlifting Top 15 All-time Medal Counts in Olympics Men's") +
    theme(
    legend.position = "bottom",
    axis.text.x = element_text(size = 6)
  )


# horizontal flip Total and medal level
weightlifting %>% 
  filter(Sex %in% "F") %>%
  count(Team, Medal) %>% 
  filter(!is.na(Medal)) %>%
  # group_by(Team) %>% 
  # mutate(medal_count = sum(n))
  spread(Medal, n, fill = 0) %>% 
  mutate(Total = Bronze + Gold + Silver) %>%
  top_n(15, wt = Total) %>% 
  gather(Medal, `medal count`, Bronze:Silver) %>% 
  mutate(
    Team = fct_reorder(Team, Total),
    Medal = fct_relevel(Medal, "Bronze", "Silver")
  ) %>% 
  ggplot(aes(Team, `medal count`, fill = Medal)) +
  geom_col(position = position_dodge2()) +
  scale_fill_manual(values = MEDAL_COLOR) +
  labs(title = "Weightlifting Top 15 All-time Medal Counts in Olympics Women's") +
  coord_flip()
```

#### Most decorated athletes

```{r, include=FALSE}
weightlifting %>%
  filter(!is.na(Medal)) %>%
  count(Name, Medal) %>%
  group_by(Name) %>%
  summarize(medal_count = sum(n)) %>%
  top_n(10, wt = medal_count) %>%
  arrange(desc(medal_count)) %>%
  kable(caption = "Most Medals")
```


```{r}
weightlifting %>% 
  filter(!is.na(Medal)) %>%
  count(Name, Medal) %>% 
  spread(Medal, n, fill = 0) %>% 
  mutate(Total = Bronze + Gold + Silver) %>% 
  select(Name, Total, Gold, Silver, Bronze) %>% 
  top_n(10, wt = Total) %>% 
  kable(caption = "Most Medals")

weightlifting %>% 
  filter(Medal %in% "Gold") %>% 
  count(Name, Medal) %>% 
  top_n(10, wt = n) %>% 
  arrange(desc(n)) %>% 
  kable(caption = "Most Golds")

weightlifting %>% 
  filter(Medal %in% "Silver") %>% 
  count(Name, Medal) %>% 
  top_n(10, wt = n) %>% 
  arrange(desc(n)) %>% 
  kable(caption = "Most Silvers")

weightlifting %>% 
  filter(Medal %in% "Bronze") %>% 
  count(Name, Medal) %>% 
  top_n(10, wt = n) %>% 
  arrange(desc(n)) %>% 
  kable(caption = "Most Bronzes")
```


## Heights

#### Height in each of the most recent weight classes Men's (2000 - 2016)

```{r}
weightlifting %>% 
  filter(
    Year > 1996,
    Sex %in% "M"
  ) %>% 
  group_by(Event) %>% 
  summarize(
    mean_height = mean(Height, na.rm = TRUE),
    mean_weight = mean(Weight, na.rm = TRUE)
  ) %>% 
  mutate(
    Event =
      str_extract(Event, "\\S+$") %>% 
      fct_reorder(mean_weight)
  ) %>% 
  ggplot(aes(Event, mean_height)) +
  geom_col() +
  scale_y_continuous(breaks = seq(0, 190, 10)) +
  labs(title = "Avg height Men's (2000 - 2016)") +
  theme(
    axis.text.x = element_text(size = 6)
  )
```

#### Height in each of the most recent weight classes Women's (2000 - 2016)

```{r}
weightlifting %>% 
  filter(
    Year > 1996,
    Sex %in% "F"
  ) %>% 
  group_by(Event) %>% 
  summarize(
    mean_height = mean(Height, na.rm = TRUE),
    mean_weight = mean(Weight, na.rm = TRUE)
  ) %>% 
  mutate(
    Event =
      str_extract(Event, "\\S+$") %>% 
      fct_reorder(mean_weight)
  ) %>% 
  ggplot(aes(Event, mean_height)) +
  geom_col() +
  scale_y_continuous(breaks = seq(0, 190, 10)) +
  labs(title = "Avg height Women's (2000 - 2016)") +
  theme(
    axis.text.x = element_text(size = 6)
  )
```

#### Height of the superheavies over the years

```{r}
weightlifting %>% 
  filter(str_detect(Event, "Men's Super-Heavyweight")) %>% 
  rbind(
    weightlifting %>% 
    filter(
      Year < 1972,
      str_detect(Event, "Men's Heavyweight")
    )
  ) %>% 
  # filter(!is.na(Height)) %>% 
  group_by(Year) %>% 
  summarize(mean_height = mean(Height, na.rm = TRUE)) %>% 
  ggplot(aes(Year, mean_height)) +
  geom_col() + 
  scale_y_continuous(breaks = seq(0, 200, 20))
```


## Weights

#### Avg weight of superheavies over the years

```{r}
weightlifting %>% 
  filter(str_detect(Event, "Men's Super-Heavyweight")) %>% 
  rbind(
    weightlifting %>% 
    filter(
      Year < 1972,
      str_detect(Event, "Men's Heavyweight")
    )
  ) %>% 
  filter(!is.na(Weight)) %>% 
  group_by(Year) %>% 
  summarize(mean_weight = mean(Weight)) %>% 
  ggplot(aes(Year, mean_weight)) +
  geom_col()
```